export const ADD_TO_CART = "add_to_cart"
export const ADJUST_QTY = "adjust_qty"
export const REMOVE_QTY = "adjust_qty"
export const REMOVE_FROM_CART = "remove_from_cart"
export const CLEAR_CART = "clear_cart"